image_width: 800
image_height: 600
camera_name: camera_01
camera_matrix:
  rows: 3
  cols: 3
  data: [ 780.66736,    0.     ,  414.07604,
            0.     ,  779.88749,  317.27058,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.348070, 0.132347, -0.000632, -0.000493, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 703.27118,    0.     ,  416.87264,    0.     ,
            0.     ,  737.35791,  319.04592,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
